{"name": "test_invalid_mobile_number_login_details[834784554764839-We cannot find an account with that mobile number]", "status": "passed", "parameters": [{"name": "username", "value": "'834784554764839'"}, {"name": "expected", "value": "'We cannot find an account with that mobile number'"}], "start": 1707709108641, "stop": 1707709111795, "uuid": "9dfaefbd-b7d2-4281-8c66-01dac68af4a8", "historyId": "19e634da22924ffce1239c52e0a5b02d", "testCaseId": "d24cb168c92779c88be90a2810ee7f46", "fullName": "test_validating_login_page_details#test_invalid_mobile_number_login_details", "labels": [{"name": "suite", "value": "test_validating_login_page_details"}, {"name": "host", "value": "vikas-Mi-NoteBook-Pro"}, {"name": "thread", "value": "3866-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_validating_login_page_details"}]}